name: Build and deploy backend

on: 
  push:
    branches:
      - master
      - main

jobs:
  build-deploy:
    name: Build and Deploy flask backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11-slim'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: coverage run manage.py

      - name: Tests report
        run: coverage report
