name: Build and deploy backend

on: 
  push:
    branches:
      - master
      
jobs:
  build-deploy:
    name: Build and Deploy flask backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./api/requirements.txt

      - name: Run tests
        run: |
          python -m unittest ./api/project/tests/test*.py

